[workspace]
members = [
    "examples/*"
]

[package]
name = "egui-file-dialog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.25.0"

# Used to fetch user folders
directories = "5.0"

# Used to fetch disks
sysinfo = { version = "0.30.5", default-features = false }
